### ISSUE TITLE
Music VAE

### ISSUE THREAD

**Issue by hadusam** [dlb2018-team16/NeuralStyleTransfer#3]
## Training
@yushinna さんがコミットしてくれたyonezuデータセットで1.5日くらい学習を回した結果、一応yonezuモデルっぽいものができた。
![スクリーンショット 2019-03-25 15 51 38](https://user-images.githubusercontent.com/12394960/54900900-4069dd80-4f18-11e9-8e2f-b386a9b8c94f.png)

このモデルを使ってランダムに生成したmidiは下記。
[run_yonezu_1.tar.gz](https://drive.google.com/file/d/1AP-IwkVn9zZ72yvzsAGrqkP4RQlK8zRs/view?usp=sharing)

それっぽいメロディが生成されているため(というか複数の曲を切って貼った感じ？)学習はうまくいっていると思われる。
が、一部、元データのMelodyそのままのような箇所がある（ランダムの空間ベクトルがたまたま元データに近いものだったのかも）

### Next
* これを使って全く別の曲同士でInterpolateしてみてyonezu感がどうなるかみてみる
* yonezu以外のbeatlesとokinawaモデルも学習してみて比較する

**Comment by yurfuwa** [comment]
東方データセット322個です。学習でご利用ください
語尾なにもなし : トラック分割無し
語尾_1 : 主旋律
語尾_2: ベース
~splited_midi.zip~
データセット公開は問題があるので削除

**Comment by yurfuwa** [comment]
東方モデルから生成した楽曲の中で、メロディがよかったものを厳選
[keep_generated.zip](https://github.com/dlb2018-team16/NeuralStyleTransfer/files/3014745/keep_generated.zip)

**Comment by hadusam** [comment]
2曲のサビの位置を合わせてMusicVAEの学習済みモデルでInterpolate(補完)をした場合、ちゃんとサビのような盛り上がりを表現できた。Aメロ、Bメロ、サビの構成を意識してそれぞれで合成すればいわゆる曲全体を合成できそう。
![image](https://user-images.githubusercontent.com/12394960/55269057-f5aee380-52d2-11e9-9c7f-a6249aa19694.png)

MusicVAEで生成したmidiはrandom sample, interpolateの両方をdriveにまとめておいておきましたー
